

Style/Encoding:
  Enabled: false

AllCops:
  Exclude:
    - 'config/**/*.rb'
    - 'bin/**'
    - 'app/**/application**.rb'
    - 'db/**/*.rb'
    - 'spec/**helper.rb'
    - 'spec/factories/**'
    - 'app/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
